# Generated by Django 5.0.5 on 2024-05-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('product', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_order',
            field=models.ManyToManyField(through='pos.orderitem', to='product.product'),
        ),
    ]
