# Generated by Django 5.0.5 on 2024-05-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
