# Generated by Django 5.0.3 on 2024-03-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='product/'),
        ),
    ]
