# Generated by Django 5.0.3 on 2024-03-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_detail_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='services/'),
        ),
    ]
